# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d15633811c18c4a00a7b3900012374d219aa435584a612fb7da37c552fc4f55e60f4a73ac37e4f8b79236d0659c036fbcf9d588e80a4e043e54a98532b3e361

test:
  secret_key_base: d3543ecf547b703a0d17533db76416d938de1f99b62d3afb1c3d71e081d7c74f37971a8ba6a46ac1b57b5de26c1bc3e1555283f1764194254e0c86b385d85eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
